### ISSUE TITLE
React 16 Support

### ISSUE THREAD

**Issue by wyattanderson** [ticky/markdown-component-loader#21]
First, thanks so much for this loader. It fits my needs perfectly. Would you please bump the React peer dependency to support React 16? Thanks! I'm using it locally with a `create-react-app`-generated app (which uses React 16) without any warnings.

**Comment by ticky** [comment]
Ah! It’s a bit behind the curve, then.

I’d be totally open to a PR which implemented this – I don’t expect I’ll get to change it over myself for a few weeks as I’m about to be travelling :)

**Comment by ticky** [comment]
Thanks! I found some time, so I’ve included your change in [v1.0.0](https://github.com/ticky/markdown-component-loader/releases/tag/v1.0.0)! :)
