### ISSUE TITLE
Error with custom JSX tag render

### ISSUE THREAD

**Issue by arcthur** [ticky/markdown-component-loader#9]
Hi, 

when I want to render custom JSX tag, that will be changed from capital to lower case. example

```jsx
<Hello name="arcthur" /> 
```

changed to 

```jsx
<hello name="arcthur />
```

and another problem that I need more complicated support to react. May be contained some complete components in one markdown.

Thanks

**Comment by ticky** [comment]
Hi there @arcthur, the intended way to use those is to put them in interpolation braces, i.e.

```jsx
{{<Hello name="arcthur" />}}
```

which should result in the correct behaviour on the current version.
